# Generated by Django 3.2.6 on 2021-09-06 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppanMedia', '0004_auto_20210906_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content1',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content2',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content3',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content4',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content5',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='head1',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='head2',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='head3',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='head4',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='head5',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='main_content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
