# Generated by Django 3.2.6 on 2021-09-06 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppanMedia', '0006_auto_20210906_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content4',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content5',
            field=models.TextField(blank=True),
        ),
    ]
