# Generated by Django 3.2.6 on 2021-09-07 02:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppanMedia', '0008_auto_20210906_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='content1',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='content2',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='content3',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='content4',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='content5',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='head1',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='head2',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='head3',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='head4',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='head5',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='main_content',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
