# Generated by Django 3.2.6 on 2021-10-02 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppanMedia', '0010_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=50)),
                ('client_feedback', models.TextField()),
                ('client_image', models.ImageField(blank=True, upload_to='images/')),
            ],
        ),
    ]
