# Generated by Django 3.2.6 on 2021-10-03 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppanMedia', '0011_testimonial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
